gender_drop = ['Overall Homeless Unaccompanied Youth (Under 25)',
 'Overall Homeless Unaccompanied Youth (Under 25) - Woman',
 'Overall Homeless Unaccompanied Youth (Under 25) - Man',
 'Overall Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Overall Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Overall Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Overall Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Overall Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Overall Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Overall Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Overall Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Overall Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Overall Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Unaccompanied Youth (Under 25) - White',
 'Overall Homeless Unaccompanied Youth (Under 25) - Multi-Racial',
 'Overall Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - White Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Overall Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25)',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Woman',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Man',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - White',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Multi-Racial',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - White Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Sheltered ES Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Woman',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Man',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - White',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Multi-Racial', 'Overall Homeless Veterans - Woman',
 'Overall Homeless Veterans - Man',
 'Overall Homeless Veterans - Transgender',
 'Overall Homeless Veterans - Gender Questioning',
 'Overall Homeless Veterans - Culturally Specific Identity',
 'Overall Homeless Veterans - Different Identity',
 'Overall Homeless Veterans - Non Binary',
 'Overall Homeless Veterans - More Than One Gender',
 'Overall Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Hispanic/Latina/e/o',
 'Overall Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless Veterans - Asian or Asian American',
 'Overall Homeless Veterans - Black, African American, or African',
 'Overall Homeless Veterans - Middle Eastern or North African',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Veterans - White',
 'Overall Homeless Veterans - Multi-Racial',
 'Overall Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Asian or Asian American Only',
 'Overall Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Black, African American, or African Only',
 'Overall Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Middle Eastern or North African Only',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless Veterans - White and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - White Only',
 'Overall Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless Veterans - Multi-Racial Only',
 'Overall Homeless Veterans - Hispanic/Latina/e/o Only',
 'Sheltered ES Homeless Veterans',
 'Sheltered ES Homeless Veterans - Woman',
 'Sheltered ES Homeless Veterans - Man',
 'Sheltered ES Homeless Veterans - Transgender',
 'Sheltered ES Homeless Veterans - Gender Questioning',
 'Sheltered ES Homeless Veterans - Culturally Specific Identity',
 'Sheltered ES Homeless Veterans - Different Identity',
 'Sheltered ES Homeless Veterans - Non Binary',
 'Sheltered ES Homeless Veterans - More Than One Gender',
 'Sheltered ES Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless Veterans - Asian or Asian American',
 'Sheltered ES Homeless Veterans - Black, African American, or African',
 'Sheltered ES Homeless Veterans - Middle Eastern or North African',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Veterans - White',
 'Sheltered ES Homeless Veterans - Multi-Racial',
 'Sheltered ES Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Asian or Asian American Only',
 'Sheltered ES Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Black, African American, or African Only',
 'Sheltered ES Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Middle Eastern or North African Only',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless Veterans - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - White Only',
 'Sheltered ES Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Veterans - Multi-Racial Only',
 'Sheltered ES Homeless Veterans - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless Veterans',
 'Sheltered TH Homeless Veterans - Woman',
 'Sheltered TH Homeless Veterans - Man',
 'Sheltered TH Homeless Veterans - Transgender',
 'Sheltered TH Homeless Veterans - Gender Questioning',
 'Sheltered TH Homeless Veterans - Culturally Specific Identity',
 'Sheltered TH Homeless Veterans - Different Identity',
 'Sheltered TH Homeless Veterans - Non Binary',
 'Sheltered TH Homeless Veterans - More Than One Gender',
 'Sheltered TH Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless Veterans - Asian or Asian American',
 'Sheltered TH Homeless Veterans - Black, African American, or African',
 'Sheltered TH Homeless Veterans - Middle Eastern or North African',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Veterans - White',
 'Sheltered TH Homeless Veterans - Multi-Racial',
 'Sheltered TH Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Asian or Asian American Only',
 'Sheltered TH Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Black, African American, or African Only',
 'Sheltered TH Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Middle Eastern or North African Only',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless Veterans - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - White Only',
 'Sheltered TH Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Veterans - Multi-Racial Only',
 'Sheltered TH Homeless Veterans - Hispanic/Latina/e/o Only',
 'Sheltered SH Homeless Veterans',
 'Sheltered SH Homeless Veterans - Woman',
 'Sheltered SH Homeless Veterans - Man',
 'Sheltered SH Homeless Veterans - Transgender',
 'Sheltered SH Homeless Veterans - Gender Questioning',
 'Sheltered SH Homeless Veterans - Culturally Specific Identity',
 'Sheltered SH Homeless Veterans - Different Identity',
 'Sheltered SH Homeless Veterans - Non Binary',
 'Sheltered SH Homeless Veterans - More Than One Gender',
 'Sheltered SH Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Sheltered SH Homeless Veterans - Asian or Asian American',
 'Sheltered SH Homeless Veterans - Black, African American, or African',
 'Sheltered SH Homeless Veterans - Middle Eastern or North African',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Veterans - White',
 'Sheltered SH Homeless Veterans - Multi-Racial',
 'Sheltered SH Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered SH Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Asian or Asian American Only',
 'Sheltered SH Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Black, African American, or African Only',
 'Sheltered SH Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Middle Eastern or North African Only',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered SH Homeless Veterans - White and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - White Only',
 'Sheltered SH Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Veterans - Multi-Racial Only',
 'Sheltered SH Homeless Veterans - Hispanic/Latina/e/o Only',
 'Sheltered Total Homeless Veterans',
 'Sheltered Total Homeless Veterans - Woman',
 'Sheltered Total Homeless Veterans - Man',
 'Sheltered Total Homeless Veterans - Transgender',
 'Sheltered Total Homeless Veterans - Gender Questioning',
 'Sheltered Total Homeless Veterans - Culturally Specific Identity',
 'Sheltered Total Homeless Veterans - Different Identity',
 'Sheltered Total Homeless Veterans - Non Binary',
 'Sheltered Total Homeless Veterans - More Than One Gender',
 'Sheltered Total Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless Veterans - Asian or Asian American',
 'Sheltered Total Homeless Veterans - Black, African American, or African',
 'Sheltered Total Homeless Veterans - Middle Eastern or North African',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Veterans - White',
 'Sheltered Total Homeless Veterans - Multi-Racial',
 'Sheltered Total Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Asian or Asian American Only',
 'Sheltered Total Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Black, African American, or African Only',
 'Sheltered Total Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Middle Eastern or North African Only',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless Veterans - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - White Only',
 'Sheltered Total Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Veterans - Multi-Racial Only',
 'Sheltered Total Homeless Veterans - Hispanic/Latina/e/o Only',
 'Unsheltered Homeless Veterans',
 'Unsheltered Homeless Veterans - Woman',
 'Unsheltered Homeless Veterans - Man',
 'Unsheltered Homeless Veterans - Transgender',
 'Unsheltered Homeless Veterans - Gender Questioning',
 'Unsheltered Homeless Veterans - Culturally Specific Identity',
 'Unsheltered Homeless Veterans - Different Identity',
 'Unsheltered Homeless Veterans - Non Binary',
 'Unsheltered Homeless Veterans - More Than One Gender',
 'Unsheltered Homeless Veterans - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless Veterans - Asian or Asian American',
 'Unsheltered Homeless Veterans - Black, African American, or African',
 'Unsheltered Homeless Veterans - Middle Eastern or North African',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Veterans - White',
 'Unsheltered Homeless Veterans - Multi-Racial',
 'Unsheltered Homeless Veterans - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless Veterans - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Asian or Asian American Only',
 'Unsheltered Homeless Veterans - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Black, African American, or African Only',
 'Unsheltered Homeless Veterans - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Middle Eastern or North African Only',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless Veterans - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - White Only',
 'Unsheltered Homeless Veterans - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless Veterans - Multi-Racial Only',
 'Unsheltered Homeless Veterans - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - White Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Sheltered TH Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25)',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Woman',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Man',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - White',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Multi-Racial',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - White Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Sheltered SH Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25)',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Woman',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Man',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - White',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Multi-Racial',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - White Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Sheltered Total Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25)',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Woman',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Man',
 'Overall Homeless - Non-Hispanic/Latina/e/o',
 'Overall Homeless - Hispanic/Latina/e/o',
 'Overall Homeless - American Indian, Alaska Native, or Indigenous ',
 'Overall Homeless - Asian or Asian American ',
 'Overall Homeless - Black, African American, or African ',
 'Overall Homeless - Middle Eastern or North African ',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander ',
 'Overall Homeless - White ',
 'Overall Homeless - Multi-Racial ',
 'Overall Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless - Asian or Asian American Only',
 'Overall Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless - Black, African American, or African Only',
 'Overall Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless - Middle Eastern or North African Only',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless - White and Hispanic/Latina/e/o',
 'Overall Homeless - White Only',
 'Overall Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless - Multi-Racial Only',
 'Overall Homeless - Hispanic/Latina/e/o Only',
 'Sheltered ES Homeless - Non-Hispanic/Latina/e/o ',
 'Sheltered ES Homeless - Hispanic/Latina/e/o ',
 'Sheltered ES Homeless - American Indian, Alaska Native, or Indigenous ',
 'Sheltered ES Homeless - Asian or Asian American ',
 'Sheltered ES Homeless - Black, African American, or African ',
 'Sheltered ES Homeless - Middle Eastern or North African ',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander ',
 'Sheltered ES Homeless - White ',
 'Sheltered ES Homeless - Multi-Racial ',
 'Sheltered ES Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Asian or Asian American Only',
 'Sheltered ES Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Black, African American, or African Only',
 'Sheltered ES Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Middle Eastern or North African Only',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - White Only',
 'Sheltered ES Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Multi-Racial Only',
 'Sheltered ES Homeless - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless - Non-Hispanic/Latina/e/o ',
 'Sheltered TH Homeless - Hispanic/Latina/e/o ',
 'Sheltered TH Homeless - American Indian, Alaska Native, or Indigenous ',
 'Sheltered TH Homeless - Asian or Asian American ',
 'Sheltered TH Homeless - Black, African American, or African ',
 'Sheltered TH Homeless - Middle Eastern or North African ',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander ',
 'Sheltered TH Homeless - White ',
 'Sheltered TH Homeless - Multi-Racial ',
 'Sheltered TH Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Asian or Asian American Only',
 'Sheltered TH Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Black, African American, or African Only',
 'Sheltered TH Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Middle Eastern or North African Only',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - White Only',
 'Sheltered TH Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Multi-Racial Only',
 'Sheltered TH Homeless - Hispanic/Latina/e/o Only',
 'Sheltered SH Homeless - Non-Hispanic/Latina/e/o ',
 'Sheltered SH Homeless - Hispanic/Latina/e/o ',
 'Sheltered SH Homeless - American Indian, Alaska Native, or Indigenous ',
 'Sheltered SH Homeless - Asian or Asian American ',
 'Sheltered SH Homeless - Black, African American, or African ',
 'Sheltered SH Homeless - Middle Eastern or North African ',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander ',
 'Sheltered SH Homeless - White ',
 'Sheltered SH Homeless - Multi-Racial ',
 'Sheltered SH Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered SH Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Asian or Asian American Only',
 'Sheltered SH Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Black, African American, or African Only',
 'Sheltered SH Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Middle Eastern or North African Only',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered SH Homeless - White and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - White Only',
 'Sheltered SH Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Multi-Racial Only',
 'Sheltered SH Homeless - Hispanic/Latina/e/o Only',
 'Sheltered Total Homeless - Non-Hispanic/Latina/e/o ',
 'Sheltered Total Homeless - Hispanic/Latina/e/o ',
 'Sheltered Total Homeless - American Indian, Alaska Native, or Indigenous ',
 'Sheltered Total Homeless - Asian or Asian American ',
 'Sheltered Total Homeless - Black, African American, or African ',
 'Sheltered Total Homeless - Middle Eastern or North African ',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander ',
 'Sheltered Total Homeless - White ',
 'Sheltered Total Homeless - Multi-Racial ',
 'Sheltered Total Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Asian or Asian American Only',
 'Sheltered Total Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Black, African American, or African Only',
 'Sheltered Total Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Middle Eastern or North African Only',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - White Only',
 'Sheltered Total Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Multi-Racial Only',
 'Sheltered Total Homeless - Hispanic/Latina/e/o Only','Sheltered ES Homeless Individuals - Under 18',
 'Sheltered ES Homeless Individuals - Age 18 to 24',
 'Sheltered ES Homeless Individuals - Over 24',
 'Sheltered ES Homeless Individuals - Age 25 to 34',
 'Sheltered ES Homeless Individuals - Age 35 to 44',
 'Sheltered ES Homeless Individuals - Age 45 to 54',
 'Sheltered ES Homeless Individuals - Age 55 to 64',
 'Sheltered ES Homeless Individuals - Over 64',
 'Sheltered ES Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless Individuals - Asian or Asian American',
 'Sheltered ES Homeless Individuals - Black, African American, or African',
 'Sheltered ES Homeless Individuals - Middle Eastern or North African',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Individuals - White',
 'Sheltered ES Homeless Individuals - Multi-Racial',
 'Sheltered ES Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Asian or Asian American Only',
 'Sheltered ES Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Black, African American, or African Only',
 'Sheltered ES Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Middle Eastern or North African Only',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless Individuals - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - White Only',
 'Sheltered ES Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Individuals - Multi-Racial Only',
 'Sheltered ES Homeless Individuals - Hispanic/Latina/e/o Only', 'Overall Homeless - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless - Asian or Asian American',
 'Overall Homeless - Black, African American, or African',
 'Overall Homeless - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless - White',
 'Overall Homeless - Multi-Racial',
 'Sheltered ES Homeless - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless - Hispanic/Latina/e/o',
 'Sheltered ES Homeless - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless - Asian or Asian American',
 'Sheltered ES Homeless - Black, African American, or African',
 'Sheltered ES Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless - White',
 'Sheltered ES Homeless - Multi-Racial',
 'Sheltered TH Homeless - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless - Hispanic/Latina/e/o',
 'Sheltered TH Homeless - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless - Asian or Asian American',
 'Sheltered TH Homeless - Black, African American, or African',
 'Sheltered TH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless - White',
 'Sheltered TH Homeless - Multi-Racial',
 'Sheltered SH Homeless - Non-Hispanic/Latina/e/o',
 'Sheltered SH Homeless - Hispanic/Latina/e/o',
 'Sheltered SH Homeless - American Indian, Alaska Native, or Indigenous',
 'Sheltered SH Homeless - Asian or Asian American',
 'Sheltered SH Homeless - Black, African American, or African',
 'Sheltered SH Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless - White',
 'Sheltered SH Homeless - Multi-Racial',
 'Sheltered Total Homeless - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless - Hispanic/Latina/e/o',
 'Sheltered Total Homeless - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless - Asian or Asian American',
 'Sheltered Total Homeless - Black, African American, or African',
 'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless - White',
 'Sheltered Total Homeless - Multi-Racial', 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Transgender',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Gender Questioning',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Culturally Specific Identity',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Different Identity',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Non Binary',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - More Than One Gender',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Asian or Asian American',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Black, African American, or African',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - White',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Multi-Racial',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Asian or Asian American Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Black, African American, or African Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Middle Eastern or North African Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - White Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Multi-Racial Only',
 'Unsheltered Homeless Unaccompanied Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Overall Homeless Unaccompanied Youth Under 18',
 'Sheltered ES Homeless Unaccompanied Youth Under 18',
 'Sheltered TH Homeless Unaccompanied Youth Under 18',
 'Sheltered SH Homeless Unaccompanied Youth Under 18',
 'Sheltered Total Homeless Unaccompanied Youth Under 18',
 'Unsheltered Homeless Unaccompanied Youth Under 18',
 'Overall Homeless Unaccompanied Youth Age 18-24',
 'Sheltered ES Homeless Unaccompanied Youth Age 18-24',
 'Sheltered TH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered SH Homeless Unaccompanied Youth Age 18-24',
 'Sheltered Total Homeless Unaccompanied Youth Age 18-24',
 'Unsheltered Homeless Unaccompanied Youth Age 18-24',
 'Overall Homeless Parenting Youth (Under 25)',
 'Overall Homeless Parenting Youth (Under 25) - Woman',
 'Overall Homeless Parenting Youth (Under 25) - Man',
 'Overall Homeless Parenting Youth (Under 25) - Transgender',
 'Overall Homeless Parenting Youth (Under 25) - Gender Questioning',
 'Overall Homeless Parenting Youth (Under 25) - Culturally Specific Identity',
 'Overall Homeless Parenting Youth (Under 25) - Different Identity',
 'Overall Homeless Parenting Youth (Under 25) - Non Binary',
 'Overall Homeless Parenting Youth (Under 25) - More Than One Gender',
 'Overall Homeless Parenting Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless Parenting Youth (Under 25) - Asian or Asian American',
 'Overall Homeless Parenting Youth (Under 25) - Black, African American, or African',
 'Overall Homeless Parenting Youth (Under 25) - Middle Eastern or North African',
 'Overall Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Parenting Youth (Under 25) - White',
 'Overall Homeless Parenting Youth (Under 25) - Multi-Racial',
 'Overall Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless Parenting Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Asian or Asian American Only',
 'Overall Homeless Parenting Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Black, African American, or African Only',
 'Overall Homeless Parenting Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Middle Eastern or North African Only',
 'Overall Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless Parenting Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - White Only',
 'Overall Homeless Parenting Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless Parenting Youth (Under 25) - Multi-Racial Only',
 'Overall Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered ES Homeless Parenting Youth (Under 25)',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Woman',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Man',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Transgender',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Gender Questioning',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Culturally Specific Identity',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Different Identity',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Non Binary',
 'Sheltered ES Homeless Parenting Youth (Under 25) - More Than One Gender',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Asian or Asian American',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Black, African American, or African',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Middle Eastern or North African',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless Parenting Youth (Under 25) - White',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Multi-Racial',
 'Sheltered ES Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Asian or Asian American Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Black, African American, or African Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - White Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Multi-Racial Only',
 'Sheltered ES Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless Parenting Youth (Under 25)',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Woman',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Man',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Transgender',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Gender Questioning',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Culturally Specific Identity',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Different Identity',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Non Binary',
 'Sheltered TH Homeless Parenting Youth (Under 25) - More Than One Gender',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Asian or Asian American',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Black, African American, or African',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Middle Eastern or North African',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Parenting Youth (Under 25) - White',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Multi-Racial',
 'Sheltered TH Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Asian or Asian American Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Black, African American, or African Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - White Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Multi-Racial Only',
 'Sheltered TH Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Sheltered Total Homeless Parenting Youth (Under 25)',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Woman',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Man',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Transgender',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Gender Questioning',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Culturally Specific Identity',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Different Identity',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Non Binary',
 'Sheltered Total Homeless Parenting Youth (Under 25) - More Than One Gender',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Asian or Asian American',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Black, African American, or African',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Middle Eastern or North African',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Parenting Youth (Under 25) - White',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Multi-Racial',
 'Sheltered Total Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Asian or Asian American Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Black, African American, or African Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Middle Eastern or North African Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - White Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Multi-Racial Only',
 'Sheltered Total Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Unsheltered Homeless Parenting Youth (Under 25)',
 'Unsheltered Homeless Parenting Youth (Under 25) - Woman',
 'Unsheltered Homeless Parenting Youth (Under 25) - Man',
 'Unsheltered Homeless Parenting Youth (Under 25) - Transgender',
 'Unsheltered Homeless Parenting Youth (Under 25) - Gender Questioning',
 'Unsheltered Homeless Parenting Youth (Under 25) - Culturally Specific Identity',
 'Unsheltered Homeless Parenting Youth (Under 25) - Different Identity',
 'Unsheltered Homeless Parenting Youth (Under 25) - Non Binary',
 'Unsheltered Homeless Parenting Youth (Under 25) - More Than One Gender',
 'Unsheltered Homeless Parenting Youth (Under 25) - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless Parenting Youth (Under 25) - Asian or Asian American',
 'Unsheltered Homeless Parenting Youth (Under 25) - Black, African American, or African',
 'Unsheltered Homeless Parenting Youth (Under 25) - Middle Eastern or North African',
 'Unsheltered Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Parenting Youth (Under 25) - White',
 'Unsheltered Homeless Parenting Youth (Under 25) - Multi-Racial',
 'Unsheltered Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Asian or Asian American Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Black, African American, or African Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Middle Eastern or North African Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - White Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless Parenting Youth (Under 25) - Multi-Racial Only',
 'Unsheltered Homeless Parenting Youth (Under 25) - Hispanic/Latina/e/o Only',
 'Overall Homeless Parenting Youth Under 18',
 'Sheltered ES Homeless Parenting Youth Under 18',
 'Sheltered TH Homeless Parenting Youth Under 18',
 'Sheltered Total Homeless Parenting Youth Under 18',
 'Unsheltered Homeless Parenting Youth Under 18',
 'Overall Homeless Parenting Youth Age 18-24',
 'Sheltered ES Homeless Parenting Youth Age 18-24',
 'Sheltered TH Homeless Parenting Youth Age 18-24',
 'Sheltered Total Homeless Parenting Youth Age 18-24',
 'Unsheltered Homeless Parenting Youth Age 18-24',
 'Overall Homeless Children of Parenting Youth',
 'Sheltered ES Homeless Children of Parenting Youth',
 'Sheltered TH Homeless Children of Parenting Youth',
 'Sheltered Total Homeless Children of Parenting Youth',
 'Unsheltered Homeless Children of Parenting Youth',
 'Unsheltered Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless Individuals - Asian or Asian American',
 'Unsheltered Homeless Individuals - Black, African American, or African',
 'Unsheltered Homeless Individuals - Middle Eastern or North African',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless Individuals - White',
 'Unsheltered Homeless Individuals - Multi-Racial',
 'Unsheltered Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Asian or Asian American Only',
 'Unsheltered Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Black, African American, or African Only',
 'Unsheltered Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Middle Eastern or North African Only',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless Individuals - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - White Only',
 'Unsheltered Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless Individuals - Multi-Racial Only',
 'Unsheltered Homeless Individuals - Hispanic/Latina/e/o Only',
 'Overall Homeless People in Families',
 'Overall Homeless People in Families - Under 18',
 'Overall Homeless People in Families - Age 18 to 24',
 'Overall Homeless People in Families - Over 24',
 'Overall Homeless People in Families - Age 25 to 34',
 'Overall Homeless People in Families - Age 35 to 44',
 'Overall Homeless People in Families - Age 45 to 54',
 'Overall Homeless People in Families - Age 55 to 64',
 'Overall Homeless People in Families - Over 64',
 'Overall Homeless People in Families - Woman',
 'Overall Homeless People in Families - Man',
 'Overall Homeless People in Families - Transgender',
 'Overall Homeless People in Families - Gender Questioning',
 'Overall Homeless People in Families - Culturally Specific Identity',
 'Overall Homeless People in Families - Different Identity',
 'Overall Homeless People in Families - Non Binary',
 'Overall Homeless People in Families - More Than One Gender',
 'Overall Homeless People in Families - Non-Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Hispanic/Latina/e/o',
 'Overall Homeless People in Families - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless People in Families - Asian or Asian American',
 'Overall Homeless People in Families - Black, African American, or African',
 'Overall Homeless People in Families - Middle Eastern or North African',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless People in Families - White',
 'Overall Homeless People in Families - Multi-Racial',
 'Overall Homeless People in Families - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless People in Families - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Asian or Asian American Only',
 'Overall Homeless People in Families - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Black, African American, or African Only',
 'Overall Homeless People in Families - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Middle Eastern or North African Only',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless People in Families - White and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - White Only',
 'Overall Homeless People in Families - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless People in Families - Multi-Racial Only',
 'Overall Homeless People in Families - Hispanic/Latina/e/o Only',
 'Sheltered ES Homeless People in Families',
 'Sheltered ES Homeless People in Families - Under 18',
 'Sheltered ES Homeless People in Families - Age 18 to 24',
 'Sheltered ES Homeless People in Families - Over 24',
 'Sheltered ES Homeless People in Families - Age 25 to 34',
 'Sheltered ES Homeless People in Families - Age 35 to 44',
 'Sheltered ES Homeless People in Families - Age 45 to 54',
 'Sheltered ES Homeless People in Families - Age 55 to 64',
 'Sheltered ES Homeless People in Families - Over 64',
 'Sheltered ES Homeless People in Families - Woman',
 'Sheltered ES Homeless People in Families - Man',
 'Sheltered ES Homeless People in Families - Transgender',
 'Sheltered ES Homeless People in Families - Gender Questioning',
 'Sheltered ES Homeless People in Families - Culturally Specific Identity',
 'Sheltered ES Homeless People in Families - Different Identity',
 'Sheltered ES Homeless People in Families - Non Binary',
 'Sheltered ES Homeless People in Families - More Than One Gender',
 'Sheltered ES Homeless People in Families - Non-Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - American Indian, Alaska Native, or Indigenous',
 'Sheltered ES Homeless People in Families - Asian or Asian American',
 'Sheltered ES Homeless People in Families - Black, African American, or African',
 'Sheltered ES Homeless People in Families - Middle Eastern or North African',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered ES Homeless People in Families - White',
 'Sheltered ES Homeless People in Families - Multi-Racial',
 'Sheltered ES Homeless People in Families - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered ES Homeless People in Families - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Asian or Asian American Only',
 'Sheltered ES Homeless People in Families - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Black, African American, or African Only',
 'Sheltered ES Homeless People in Families - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Middle Eastern or North African Only',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered ES Homeless People in Families - White and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - White Only',
 'Sheltered ES Homeless People in Families - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered ES Homeless People in Families - Multi-Racial Only',
 'Sheltered ES Homeless People in Families - Hispanic/Latina/e/o Only',
 'Sheltered TH Homeless People in Families',
 'Sheltered TH Homeless People in Families - Under 18',
 'Sheltered TH Homeless People in Families - Age 18 to 24',
 'Sheltered TH Homeless People in Families - Over 24',
 'Sheltered TH Homeless People in Families - Age 25 to 34',
 'Sheltered TH Homeless People in Families - Age 35 to 44',
 'Sheltered TH Homeless People in Families - Age 45 to 54',
 'Sheltered TH Homeless People in Families - Age 55 to 64',
 'Sheltered TH Homeless People in Families - Over 64',
 'Sheltered TH Homeless People in Families - Woman',
 'Sheltered TH Homeless People in Families - Man',
 'Sheltered TH Homeless People in Families - Transgender',
 'Sheltered TH Homeless People in Families - Gender Questioning',
 'Sheltered TH Homeless People in Families - Culturally Specific Identity',
 'Sheltered TH Homeless People in Families - Different Identity',
 'Sheltered TH Homeless People in Families - Non Binary',
 'Sheltered TH Homeless People in Families - More Than One Gender',
 'Sheltered TH Homeless People in Families - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless People in Families - Asian or Asian American',
 'Sheltered TH Homeless People in Families - Black, African American, or African',
 'Sheltered TH Homeless People in Families - Middle Eastern or North African',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless People in Families - White',
 'Sheltered TH Homeless People in Families - Multi-Racial',
 'Sheltered TH Homeless People in Families - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless People in Families - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Asian or Asian American Only',
 'Sheltered TH Homeless People in Families - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Black, African American, or African Only',
 'Sheltered TH Homeless People in Families - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Middle Eastern or North African Only',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless People in Families - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - White Only',
 'Sheltered TH Homeless People in Families - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless People in Families - Multi-Racial Only',
 'Sheltered TH Homeless People in Families - Hispanic/Latina/e/o Only',
 'Sheltered Total Homeless People in Families',
 'Sheltered Total Homeless People in Families - Under 18',
 'Sheltered Total Homeless People in Families - Age 18 to 24',
 'Sheltered Total Homeless People in Families - Over 24',
 'Sheltered Total Homeless People in Families - Age 25 to 34',
 'Sheltered Total Homeless People in Families - Age 35 to 44',
 'Sheltered Total Homeless People in Families - Age 45 to 54',
 'Sheltered Total Homeless People in Families - Age 55 to 64',
 'Sheltered Total Homeless People in Families - Over 64',
 'Sheltered Total Homeless People in Families - Woman',
 'Sheltered Total Homeless People in Families - Man',
 'Sheltered Total Homeless People in Families - Transgender',
 'Sheltered Total Homeless People in Families - Gender Questioning',
 'Sheltered Total Homeless People in Families - Culturally Specific Identity',
 'Sheltered Total Homeless People in Families - Different Identity',
 'Sheltered Total Homeless People in Families - Non Binary',
 'Sheltered Total Homeless People in Families - More Than One Gender',
 'Sheltered Total Homeless People in Families - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless People in Families - Asian or Asian American',
 'Sheltered Total Homeless People in Families - Black, African American, or African',
 'Sheltered Total Homeless People in Families - Middle Eastern or North African',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless People in Families - White',
 'Sheltered Total Homeless People in Families - Multi-Racial',
 'Sheltered Total Homeless People in Families - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless People in Families - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Asian or Asian American Only',
 'Sheltered Total Homeless People in Families - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Black, African American, or African Only',
 'Sheltered Total Homeless People in Families - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Middle Eastern or North African Only',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless People in Families - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - White Only',
 'Sheltered Total Homeless People in Families - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless People in Families - Multi-Racial Only',
 'Sheltered Total Homeless People in Families - Hispanic/Latina/e/o Only',
 'Unsheltered Homeless People in Families',
 'Unsheltered Homeless People in Families - Under 18',
 'Unsheltered Homeless People in Families - Age 18 to 24',
 'Unsheltered Homeless People in Families - Over 24',
 'Unsheltered Homeless People in Families - Age 25 to 34',
 'Unsheltered Homeless People in Families - Age 35 to 44',
 'Unsheltered Homeless People in Families - Age 45 to 54',
 'Unsheltered Homeless People in Families - Age 55 to 64',
 'Unsheltered Homeless People in Families - Over 64',
 'Unsheltered Homeless People in Families - Woman',
 'Unsheltered Homeless People in Families - Man',
 'Unsheltered Homeless People in Families - Transgender',
 'Unsheltered Homeless People in Families - Gender Questioning',
 'Unsheltered Homeless People in Families - Culturally Specific Identity',
 'Unsheltered Homeless People in Families - Different Identity',
 'Unsheltered Homeless People in Families - Non Binary',
 'Unsheltered Homeless People in Families - More Than One Gender',
 'Unsheltered Homeless People in Families - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless People in Families - Asian or Asian American',
 'Unsheltered Homeless People in Families - Black, African American, or African',
 'Unsheltered Homeless People in Families - Middle Eastern or North African',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless People in Families - White',
 'Unsheltered Homeless People in Families - Multi-Racial',
 'Unsheltered Homeless People in Families - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless People in Families - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Asian or Asian American Only',
 'Unsheltered Homeless People in Families - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Black, African American, or African Only',
 'Unsheltered Homeless People in Families - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Middle Eastern or North African Only',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless People in Families - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - White Only',
 'Unsheltered Homeless People in Families - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless People in Families - Multi-Racial Only',
 'Unsheltered Homeless People in Families - Hispanic/Latina/e/o Only',
 'Overall Homeless Family Households',
 'Sheltered ES Homeless Family Households',
 'Sheltered TH Homeless Family Households',
 'Sheltered Total Homeless Family Households',
 'Unsheltered Homeless Family Households',
 'Overall Chronically Homeless',
 'Sheltered ES Chronically Homeless',
 'Sheltered SH Chronically Homeless',
 'Sheltered Total Chronically Homeless',
 'Unsheltered Chronically Homeless',
 'Overall Chronically Homeless Individuals',
 'Sheltered ES Chronically Homeless Individuals',
 'Sheltered SH Chronically Homeless Individuals',
 'Sheltered Total Chronically Homeless Individuals',
 'Unsheltered Chronically Homeless Individuals',
 'Overall Chronically Homeless People in Families',
 'Sheltered ES Chronically Homeless People in Families',
 'Sheltered Total Chronically Homeless People in Families',
 'Unsheltered Chronically Homeless People in Families',
 'Unsheltered Homeless - Non-Hispanic/Latina/e/o',
 'Unsheltered Homeless - Hispanic/Latina/e/o',
 'Unsheltered Homeless - American Indian, Alaska Native, or Indigenous',
 'Unsheltered Homeless - Asian or Asian American',
 'Unsheltered Homeless - Black, African American, or African',
 'Unsheltered Homeless - Middle Eastern or North African',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander',
 'Unsheltered Homeless - White',
 'Unsheltered Homeless - Multi-Racial',
 'Unsheltered Homeless - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Unsheltered Homeless - American Indian, Alaska Native, or Indigenous Only',
 'Unsheltered Homeless - Asian or Asian American and Hispanic/Latina/e/o',
 'Unsheltered Homeless - Asian or Asian American Only',
 'Unsheltered Homeless - Black, African American, or African and Hispanic/Latina/e/o',
 'Unsheltered Homeless - Black, African American, or African Only',
 'Unsheltered Homeless - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Unsheltered Homeless - Middle Eastern or North African Only',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Unsheltered Homeless - Native Hawaiian or Other Pacific Islander Only',
 'Unsheltered Homeless - White and Hispanic/Latina/e/o',
 'Unsheltered Homeless - White Only',
 'Unsheltered Homeless - Multi-Racial and Hispanic/Latina/e/o',
 'Unsheltered Homeless - Multi-Racial Only',
 'Unsheltered Homeless - Hispanic/Latina/e/o Only',
'Overall Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Hispanic/Latina/e/o',
 'Overall Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Overall Homeless Individuals - Asian or Asian American',
 'Overall Homeless Individuals - Black, African American, or African',
 'Overall Homeless Individuals - Middle Eastern or North African',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Overall Homeless Individuals - White',
 'Overall Homeless Individuals - Multi-Racial',
 'Overall Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Overall Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Asian or Asian American Only',
 'Overall Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Black, African American, or African Only',
 'Overall Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Middle Eastern or North African Only',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Overall Homeless Individuals - White and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - White Only',
 'Overall Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Overall Homeless Individuals - Multi-Racial Only',
 'Overall Homeless Individuals - Hispanic/Latina/e/o Only',
'Sheltered TH Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Sheltered TH Homeless Individuals - Asian or Asian American',
 'Sheltered TH Homeless Individuals - Black, African American, or African',
 'Sheltered TH Homeless Individuals - Middle Eastern or North African',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered TH Homeless Individuals - White',
 'Sheltered TH Homeless Individuals - Multi-Racial',
 'Sheltered TH Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered TH Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Asian or Asian American Only',
 'Sheltered TH Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Black, African American, or African Only',
 'Sheltered TH Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Middle Eastern or North African Only',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered TH Homeless Individuals - White and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - White Only',
 'Sheltered TH Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered TH Homeless Individuals - Multi-Racial Only',
 'Sheltered TH Homeless Individuals - Hispanic/Latina/e/o Only',
'Sheltered SH Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Sheltered SH Homeless Individuals - Asian or Asian American',
 'Sheltered SH Homeless Individuals - Black, African American, or African',
 'Sheltered SH Homeless Individuals - Middle Eastern or North African',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered SH Homeless Individuals - White',
 'Sheltered SH Homeless Individuals - Multi-Racial',
 'Sheltered SH Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered SH Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Asian or Asian American Only',
 'Sheltered SH Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Black, African American, or African Only',
 'Sheltered SH Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Middle Eastern or North African Only',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered SH Homeless Individuals - White and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - White Only',
 'Sheltered SH Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered SH Homeless Individuals - Multi-Racial Only',
 'Sheltered SH Homeless Individuals - Hispanic/Latina/e/o Only', 'Sheltered Total Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless Individuals - Asian or Asian American',
 'Sheltered Total Homeless Individuals - Black, African American, or African',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Individuals - White',
 'Sheltered Total Homeless Individuals - Multi-Racial',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Asian or Asian American Only',
 'Sheltered Total Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Black, African American, or African Only',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African Only',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless Individuals - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - White Only',
 'Sheltered Total Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Multi-Racial Only',
 'Sheltered Total Homeless Individuals - Hispanic/Latina/e/o Only','Sheltered Total Homeless Individuals - Non-Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous',
 'Sheltered Total Homeless Individuals - Asian or Asian American',
 'Sheltered Total Homeless Individuals - Black, African American, or African',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander',
 'Sheltered Total Homeless Individuals - White',
 'Sheltered Total Homeless Individuals - Multi-Racial',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - American Indian, Alaska Native, or Indigenous Only',
 'Sheltered Total Homeless Individuals - Asian or Asian American and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Asian or Asian American Only',
 'Sheltered Total Homeless Individuals - Black, African American, or African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Black, African American, or African Only',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Middle Eastern or North African Only',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Native Hawaiian or Other Pacific Islander Only',
 'Sheltered Total Homeless Individuals - White and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - White Only',
 'Sheltered Total Homeless Individuals - Multi-Racial and Hispanic/Latina/e/o',
 'Sheltered Total Homeless Individuals - Multi-Racial Only',
 'Sheltered Total Homeless Individuals - Hispanic/Latina/e/o Only',
                                                  

                                                  
                                                  
 'Overall Homeless - Under 18',
 'Overall Homeless - Age 18 to 24',
 'Overall Homeless - Over 24',
 'Overall Homeless - Age 25 to 34',
 'Overall Homeless - Age 35 to 44',
 'Overall Homeless - Age 45 to 54',
 'Overall Homeless - Age 55 to 64',
 'Overall Homeless - Over 64',
 'Sheltered ES Homeless - Under 18',
 'Sheltered ES Homeless - Age 18 to 24',
 'Sheltered ES Homeless - Over 24',
 'Sheltered ES Homeless - Age 25 to 34',
 'Sheltered ES Homeless - Age 35 to 44',
 'Sheltered ES Homeless - Age 45 to 54',
 'Sheltered ES Homeless - Age 55 to 64',
 'Sheltered ES Homeless - Over 64', 'Sheltered TH Homeless - Under 18',
 'Sheltered TH Homeless - Age 18 to 24',
 'Sheltered TH Homeless - Over 24',
 'Sheltered TH Homeless - Age 25 to 34',
 'Sheltered TH Homeless - Age 35 to 44',
 'Sheltered TH Homeless - Age 45 to 54',
 'Sheltered TH Homeless - Age 55 to 64',
 'Sheltered TH Homeless - Over 64', 'Sheltered SH Homeless - Under 18',
 'Sheltered SH Homeless - Age 18 to 24',
 'Sheltered SH Homeless - Over 24',
 'Sheltered SH Homeless - Age 25 to 34',
 'Sheltered SH Homeless - Age 35 to 44',
 'Sheltered SH Homeless - Age 45 to 54',
 'Sheltered SH Homeless - Age 55 to 64',
 'Sheltered SH Homeless - Over 64',          'Sheltered Total Homeless - Under 18',
 'Sheltered Total Homeless - Age 18 to 24',
 'Sheltered Total Homeless - Over 24',
 'Sheltered Total Homeless - Age 25 to 34',
 'Sheltered Total Homeless - Age 35 to 44',
 'Sheltered Total Homeless - Age 45 to 54',
 'Sheltered Total Homeless - Age 55 to 64',
 'Sheltered Total Homeless - Over 64',
  'Unsheltered Homeless - Under 18',
 'Unsheltered Homeless - Age 18 to 24',
 'Unsheltered Homeless - Over 24',
 'Unsheltered Homeless - Age 25 to 34',
 'Unsheltered Homeless - Age 35 to 44',
 'Unsheltered Homeless - Age 45 to 54',
 'Unsheltered Homeless - Age 55 to 64',
 'Unsheltered Homeless - Over 64','Overall Homeless Individuals - Under 18',
 'Overall Homeless Individuals - Age 18 to 24',
 'Overall Homeless Individuals - Over 24',
 'Overall Homeless Individuals - Age 25 to 34',
 'Overall Homeless Individuals - Age 35 to 44',
 'Overall Homeless Individuals - Age 45 to 54',
 'Overall Homeless Individuals - Age 55 to 64',
 'Overall Homeless Individuals - Over 64','Sheltered TH Homeless Individuals - Under 18',
 'Sheltered TH Homeless Individuals - Age 18 to 24',
 'Sheltered TH Homeless Individuals - Over 24',
 'Sheltered TH Homeless Individuals - Age 25 to 34',
 'Sheltered TH Homeless Individuals - Age 35 to 44',
 'Sheltered TH Homeless Individuals - Age 45 to 54',
 'Sheltered TH Homeless Individuals - Age 55 to 64',
 'Sheltered TH Homeless Individuals - Over 64','Sheltered SH Homeless Individuals - Under 18',
 'Sheltered SH Homeless Individuals - Age 18 to 24',
 'Sheltered SH Homeless Individuals - Over 24',
 'Sheltered SH Homeless Individuals - Age 25 to 34',
 'Sheltered SH Homeless Individuals - Age 35 to 44',
 'Sheltered SH Homeless Individuals - Age 45 to 54',
 'Sheltered SH Homeless Individuals - Age 55 to 64',
 'Sheltered SH Homeless Individuals - Over 64', 'Sheltered Total Homeless Individuals - Under 18',
 'Sheltered Total Homeless Individuals - Age 18 to 24',
 'Sheltered Total Homeless Individuals - Over 24',
 'Sheltered Total Homeless Individuals - Age 25 to 34',
 'Sheltered Total Homeless Individuals - Age 35 to 44',
 'Sheltered Total Homeless Individuals - Age 45 to 54',
 'Sheltered Total Homeless Individuals - Age 55 to 64',
 'Sheltered Total Homeless Individuals - Over 64','Unsheltered Homeless Individuals - Under 18',
 'Unsheltered Homeless Individuals - Age 18 to 24',
 'Unsheltered Homeless Individuals - Over 24',
 'Unsheltered Homeless Individuals - Age 25 to 34',
 'Unsheltered Homeless Individuals - Age 35 to 44',
 'Unsheltered Homeless Individuals - Age 45 to 54',
 'Unsheltered Homeless Individuals - Age 55 to 64',
 'Unsheltered Homeless Individuals - Over 64','Number of CoCs',
 'Overall Homeless',
 'Overall Homeless - Woman',
 'Overall Homeless - Man',
 'Overall Homeless - Transgender',
 'Overall Homeless - Gender Questioning',
 'Overall Homeless - Culturally Specific Identity',
 'Overall Homeless - Different Identity',
 'Overall Homeless - Non Binary',
 'Overall Homeless - More Than One Gender',
 'Sheltered ES Homeless',
 'Sheltered ES Homeless - Woman',
 'Sheltered ES Homeless - Man',
 'Sheltered ES Homeless - Transgender',
 'Sheltered ES Homeless - Gender Questioning',
 'Sheltered ES Homeless - Culturally Specific Identity',
 'Sheltered ES Homeless - Different Identity',
 'Sheltered ES Homeless - Non Binary',
 'Sheltered ES Homeless - More Than One Gender',
 'Sheltered TH Homeless',
 'Sheltered TH Homeless - Woman',
 'Sheltered TH Homeless - Man',
 'Sheltered TH Homeless - Transgender',
 'Sheltered TH Homeless - Gender Questioning',
 'Sheltered TH Homeless - Culturally Specific Identity',
 'Sheltered TH Homeless - Different Identity',
 'Sheltered TH Homeless - Non Binary',
 'Sheltered TH Homeless - More Than One Gender',
 'Sheltered SH Homeless',
 'Sheltered SH Homeless - Woman',
 'Sheltered SH Homeless - Man',
 'Sheltered SH Homeless - Transgender',
 'Sheltered SH Homeless - Gender Questioning',
 'Sheltered SH Homeless - Culturally Specific Identity',
 'Sheltered SH Homeless - Different Identity',
 'Sheltered SH Homeless - Non Binary',
 'Sheltered SH Homeless - More Than One Gender',
 'Sheltered Total Homeless',
 'Sheltered Total Homeless - Woman',
 'Sheltered Total Homeless - Man',
 'Sheltered Total Homeless - Transgender',
 'Sheltered Total Homeless - Gender Questioning',
 'Sheltered Total Homeless - Culturally Specific Identity',
 'Sheltered Total Homeless - Different Identity',
 'Sheltered Total Homeless - Non Binary',
 'Sheltered Total Homeless - More Than One Gender',
 'Unsheltered Homeless',
 'Unsheltered Homeless - Woman',
 'Unsheltered Homeless - Man',
 'Unsheltered Homeless - Transgender',
 'Unsheltered Homeless - Gender Questioning',
 'Unsheltered Homeless - Culturally Specific Identity',
 'Unsheltered Homeless - Different Identity',
 'Unsheltered Homeless - Non Binary',
 'Unsheltered Homeless - More Than One Gender','Overall Homeless Veterans']


