hic_drop = [ 'Total Year-Round Beds (RRH & DEM)',
 'Total Non-DV Year-Round Beds (RRH & DEM)',
 'Total HMIS Year-Round Beds (RRH & DEM)',
 'HMIS Participation Rate for Year-Round Beds (RRH & DEM)',
 'Total Units for Households with Children (RRH & DEM)',
 'Total Beds for Households with Children (RRH & DEM)',
 'Total Beds for Households without Children (RRH & DEM)',
 'Total Beds for Households with only Children (RRH & DEM)',
 'Total Year-Round Beds (DEM)',
 'Total Non-DV Year-Round Beds (DEM)',
 'Total HMIS Year-Round Beds (DEM)',
 'HMIS Participation Rate for Year-Round Beds (DEM)',
 'Total Units for Households with Children (DEM)',
 'Total Beds for Households with Children (DEM)',
 'Total Beds for Households without Children (DEM)',
 'Total Beds for Households with only Children (DEM)', 'HMIS Participation Rate for Year-Round Beds (OPH)',
 'Total Units for Households with Children (OPH)',
 'Total Beds for Households with Children (OPH)',
 'Total Beds for Households without Children (OPH)',
 'Total Beds for Households with only Children (OPH)',
 'Dedicated Veteran Beds (OPH)',
 'Dedicated Youth Beds (OPH)', 'HMIS Participation Rate for Year-Round Beds (PSH)',
 'Total Units for Households with Children (PSH)',
 'Total Beds for Households with Children (PSH)',
 'Total Beds for Households without Children (PSH)',
 'Total Beds for Households with only Children (PSH)',
 'Dedicated Veteran Beds (PSH)',
 'Dedicated Youth Beds (PSH)',
 'Dedicated Chronically Homeless Beds (PSH)',
 'Total Year-Round Beds (OPH)',
 'Total Non-DV Year-Round Beds (OPH)','HMIS Participation Rate for Year-Round Beds (SH)',
 'Total Units for Households with Children (SH)',
 'Total Beds for Households with Children (SH)',
 'Total Beds for Households without Children (SH)',
 'Total Beds for Households with only Children (SH)',
 'Dedicated Veteran Beds (SH)',
 'Dedicated Youth Beds (SH)',
 'Total Year-Round Beds (RRH)',
 'Total Non-DV Year-Round Beds (RRH)',
 'Total HMIS Year-Round Beds (RRH)',
 'HMIS Participation Rate for Year-Round Beds (RRH)',
 'Total Units for Households with Children (RRH)',
 'Total Beds for Households with Children (RRH)',
 'Total Beds for Households without Children (RRH)',
 'Total Beds for Households with only Children (RRH)',
 'Dedicated Veteran Beds (RRH)',
 'Dedicated Youth Beds (RRH)',
 'Total Year-Round Beds (PSH)',
 'Total Non-DV Year-Round Beds (PSH)', 'HMIS Participation Rate for Year-Round Beds (TH)',
 'Total Units for Households with Children (TH)',
 'Total Beds for Households with Children (TH)',
 'Total Beds for Households without Children (TH)',
 'Total Beds for Households with only Children (TH)',
 'Dedicated Veteran Beds (TH)',
 'Dedicated Youth Beds (TH)',
 'Total Year-Round Beds (SH).1',
 'Total Non-DV Year-Round Beds (SH)', 'HMIS Participation Rate for Year-Round Beds (ES)',
 'Total Seasonal Beds (ES)',
 'Total Overflow Beds (ES)',
 'Total Units for Households with Children (ES)',
 'Total Beds for Households with Children (ES)',
 'Total Beds for Households without Children (ES)',
 'Total Beds for Households with only Children (ES)',
 'Dedicated Veteran Beds (ES)',
 'Dedicated Youth Beds (ES)',
 'Total Year-Round Beds (TH).1',
 'Total Non-DV Year-Round Beds (TH)', 'Total Units for Households with Children (ES, TH, SH)',
 'Total Beds for Households with Children (ES, TH, SH)',
 'Total Beds for Households without Children (ES, TH, SH)',
 'Total Beds for Households with only Children (ES, TH, SH)',
 'Dedicated Veteran Beds (ES, TH, SH)',
 'Dedicated Youth Beds (ES, TH, SH)',
 'Total Year-Round Beds (ES).1',
 'Total Non-DV Year-Round Beds (ES)','Total Year-Round Beds (ES, TH, SH)',
 'Total Non-DV Year-Round Beds (ES, TH, SH)','Total Year-Round Beds (ES)',
 'Total Year-Round Beds (TH)',
 'Total Year-Round Beds (SH)',]
