ca_noncis_drop = ['State',
'Overall Homeless Individuals - Woman',
 'Overall Homeless Individuals - Man',
 'Overall Homeless Individuals - Transgender',
 'Overall Homeless Individuals - Gender Questioning',
 'Overall Homeless Individuals - Culturally Specific Identity',
 'Overall Homeless Individuals - Different Identity',
 'Overall Homeless Individuals - Non Binary',
 'Overall Homeless Individuals - More Than One Gender',
 'Sheltered ES Homeless Individuals',
 'Sheltered ES Homeless Individuals - Woman',
 'Sheltered ES Homeless Individuals - Man',
 'Sheltered ES Homeless Individuals - Transgender',
 'Sheltered ES Homeless Individuals - Gender Questioning',
 'Sheltered ES Homeless Individuals - Culturally Specific Identity',
 'Sheltered ES Homeless Individuals - Different Identity',
 'Sheltered ES Homeless Individuals - Non Binary',
 'Sheltered ES Homeless Individuals - More Than One Gender',
 'Sheltered TH Homeless Individuals',
 'Sheltered TH Homeless Individuals - Woman',
 'Sheltered TH Homeless Individuals - Man',
 'Sheltered TH Homeless Individuals - Transgender',
 'Sheltered TH Homeless Individuals - Gender Questioning',
 'Sheltered TH Homeless Individuals - Culturally Specific Identity',
 'Sheltered TH Homeless Individuals - Different Identity',
 'Sheltered TH Homeless Individuals - Non Binary',
 'Sheltered TH Homeless Individuals - More Than One Gender',
 'Sheltered SH Homeless Individuals',
 'Sheltered SH Homeless Individuals - Woman',
 'Sheltered SH Homeless Individuals - Man',
 'Sheltered SH Homeless Individuals - Transgender',
 'Sheltered SH Homeless Individuals - Gender Questioning',
 'Sheltered SH Homeless Individuals - Culturally Specific Identity',
 'Sheltered SH Homeless Individuals - Different Identity',
 'Sheltered SH Homeless Individuals - Non Binary',
 'Sheltered SH Homeless Individuals - More Than One Gender',
 'Sheltered Total Homeless Individuals',
 'Sheltered Total Homeless Individuals - Woman',
 'Sheltered Total Homeless Individuals - Man',
 'Sheltered Total Homeless Individuals - Transgender',
 'Sheltered Total Homeless Individuals - Gender Questioning',
 'Sheltered Total Homeless Individuals - Culturally Specific Identity',
 'Sheltered Total Homeless Individuals - Different Identity',
 'Sheltered Total Homeless Individuals - Non Binary',
 'Sheltered Total Homeless Individuals - More Than One Gender',
 'Unsheltered Homeless Individuals',
 'Unsheltered Homeless Individuals - Woman',
 'Unsheltered Homeless Individuals - Man',
 'Unsheltered Homeless Individuals - Transgender',
 'Unsheltered Homeless Individuals - Gender Questioning',
 'Unsheltered Homeless Individuals - Culturally Specific Identity',
 'Unsheltered Homeless Individuals - Different Identity',
 'Unsheltered Homeless Individuals - Non Binary',
 'Unsheltered Homeless Individuals - More Than One Gender','Non-Cisgender %',]


